<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" total="2" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="13043" started-at="2016-04-20T09:34:33Z" finished-at="2016-04-20T09:34:46Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="13043" started-at="2016-04-20T09:34:33Z" finished-at="2016-04-20T09:34:46Z">
      <class name="framwrk.Datadrvn">
        <test-method status="FAIL" signature="loginFb(java.lang.String, java.lang.String)[pri:0, instance:framwrk.Datadrvn@483bf400]" name="loginFb" duration-ms="6905" started-at="2016-04-20T15:04:33Z" data-provider="Facebook" finished-at="2016-04-20T15:04:40Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[admin]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[123]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Problem loading page] but found [Problem loading page]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Problem loading page] but found [Problem loading page]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotSame(Assert.java:509)
	at org.testng.Assert.assertSame(Assert.java:460)
	at org.testng.Assert.assertSame(Assert.java:470)
	at framwrk.Datadrvn.loginFb(Datadrvn.java:20)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginFb -->
        <test-method status="PASS" signature="end()[pri:0, instance:framwrk.Datadrvn@483bf400]" name="end" is-config="true" duration-ms="141" started-at="2016-04-20T15:04:40Z" finished-at="2016-04-20T15:04:40Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- end -->
        <test-method status="FAIL" signature="loginFb(java.lang.String, java.lang.String)[pri:0, instance:framwrk.Datadrvn@483bf400]" name="loginFb" duration-ms="5832" started-at="2016-04-20T15:04:40Z" data-provider="Facebook" finished-at="2016-04-20T15:04:46Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[agila2612@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[abcd]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Problem loading page] but found [Problem loading page]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Problem loading page] but found [Problem loading page]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotSame(Assert.java:509)
	at org.testng.Assert.assertSame(Assert.java:460)
	at org.testng.Assert.assertSame(Assert.java:470)
	at framwrk.Datadrvn.loginFb(Datadrvn.java:20)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginFb -->
        <test-method status="PASS" signature="end()[pri:0, instance:framwrk.Datadrvn@483bf400]" name="end" is-config="true" duration-ms="135" started-at="2016-04-20T15:04:46Z" finished-at="2016-04-20T15:04:46Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- end -->
      </class> <!-- framwrk.Datadrvn -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
